export const GET_ALL_STUDENT = "GET_ALL_STUDENT";
export const GET_STUDENT_DETAIL = "GET_STUDENT_DETAIL";
export const PUT_STUDENT_DETAIL = "PUT_STUDENT_DETAIL";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const ALPHABETICAL_SORT = "ALPHABETICAL_SORT";
export const FILTER_INTEREST = "FILTER_INTEREST";
